name: basispaysdk
description: Flutter SDK kit for payment gateway transactions within India
version: 1.1.1
homepage: "https://github.com/Baabujiventuress/fluttersdk"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.basispaysdk
        pluginClass: BasispaysdkPlugin
      ios:
        pluginClass: BasispaysdkPlugin

